type = "webhook"
schemaVersion = 1
name = "ETH Price Fetcher"
externalJobID = "b1d42cd5-4a3a-4200-b1f7-25a68e48aad8"
evmChainID = 1337
maxTaskDuration = "30s"
observationSource = """
    fetch    [type="http" method=GET url="https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=usd"]
    parse    [type="jsonparse" path="ethereum,usd"]
    multiply [type="multiply" times=100]
    output   [type="logger"]

    fetch -> parse -> multiply -> output
"""