type = "directrequest"
schemaVersion = 1
name = "Local ETH Price Fetch Log"
externalJobID = "ca98366c-c731-4957-b8c0-12c72f05aeea"
evmChainID = 1337
maxTaskDuration = "30s"

observationSource = """
    get_price     [type=http method=GET url="https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=usd" responseFormat="json"]
    parse_price   [type=jsonparse path="ethereum.usd" input="$(get_price)"]
    multiply      [type=multiply input="$(parse_price)" times=100]
    log_result    [type=log input="$(multiply)"]

    get_price -> parse_price -> multiply -> log_result
"""