type = "webhook"
schemaVersion = 1
name = "Local ETH Price Fetcher"
externalJobID = "ca98366c-c731-4957-b8c0-12c72f05aeea"
maxTaskDuration = "30s"
observationSource = """
    fetch          [type=http method=GET url="https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=usd"]
    parse          [type=jsonparse path="ethereum,usd"]
    multiply       [type=multiply input="$(parse)" times=100]
    encode         [type=jsonencode input="$(multiply)"]
    log            [type=bridge name="log" input="$(encode)"]

    fetch -> parse -> multiply -> encode -> log
"""