type = "directrequest"
schemaVersion = 1
name = "Test aleatorio"
externalJobID = "ad23fcf5-3dae-4a44-a6b0-87b576908a79"
forwardingAllowed = false
maxTaskDuration = "0s"
contractAddress = "0xc970705401D0D61A05d49C33ab2A39A5C49b2f94"
evmChainID = "1337"
minIncomingConfirmations = 0
minContractPaymentLinkJuels = "0"
observationSource = """
    fetch    [type="http" method=GET url="https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=usd"]
    parse    [type="jsonparse" path="ethereum,usd"]
    multiply [type="multiply" input="$(parse)" times=100]
    fetch -> parse -> multiply
"""